DROP SEQUENCE BOARDNOSQ;
DROP SEQUENCE GROUPNOSQ;

DROP TABLE ANSWERBOARD;

--글 번호 시퀀스(PRIMARY KEY)
CREATE SEQUENCE BOARDNOSQ;

--그룹 번호 시퀀스 그룹 번호 시퀀스 (새로운 글 등록할 때만)
CREATE SEQUENCE GROUPNOSQ;

--글 번호, 그룹번호, 그룹순서 , 제목텝, 제목 ,내용,작성자 , 작성일
CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(1000) NOT NULL,
	ISDEL VARCHAR2(2) CHECK(ISDEL IN('Y','N')) NOT NULL,
	REGDATE DATE NOT NULL
);

SELECT * FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSQ;


INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,
1,0,'첫번째 글', '1번 글 입니다 ', '유저1' , 'N',SYSDATE
);


INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,
1,0,'두번째 글', '2번 글 입니다 ', '유저2' , SYSDATE
);

--답글 작성(1번글에)

--부모와 같은 그룹넘버
--부모의 그룹SQ+1, 부모의 TITLETAB+1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, (SELECT GROUPNO FROM ANSWERBOARD 
 WHERE BOARDNO=1),
(SELECT GROUPSQ FROM ANSWERBOARD 
 WHERE BOARDNO=1)+1,
(SELECT TITLETAB FROM ANSWERBOARD 
 WHERE BOARDNO=1)+1,'RE:첫번째 글', '1번글에 답글입니다 ', '유저2' , SYSDATE
);

--3번째 글
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, GROUPNOSQ.NEXTVAL,
1,0,'세번째 글', '3번 글 입니다 ', '유저3' , SYSDATE
);

--2번쨰 답글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, (SELECT GROUPNO FROM ANSWERBOARD 
 WHERE BOARDNO=1)+1,
(SELECT GROUPSQ FROM ANSWERBOARD 
 WHERE BOARDNO=1)+1,
(SELECT TITLETAB FROM ANSWERBOARD 
 WHERE BOARDNO=1)+1,'RE:두번째 글', '2번글에 답글입니다 ', '유저1' , SYSDATE
);

--답글 작성(RE:두번쨰글-5)
--부모와 같은 그룹넘버
--부모의 그룹 +1 , 부모의 타이틀 +1
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, (SELECT GROUPNO FROM ANSWERBOARD 
 WHERE BOARDNO=5),
(SELECT GROUPSQ FROM ANSWERBOARD 
 WHERE BOARDNO=5)+1,
(SELECT TITLETAB FROM ANSWERBOARD 
 WHERE BOARDNO=5)+1,'RE:RE:두번째 글', '2번글에 답글입니다(1) ', '유저2' , SYSDATE
);

--답글 작성 (두번째 글 -2)

--부모와 같은 그룹넘버, 
--부모의 그롭SQ보다 큰 글들의 그룹 SQ+1

UPDATE ANSWERBOARD SET GROUPSQ = GROUPSQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=8) 
AND GROUPSQ > (SELECT GROUPSQ FROM ANSWERBOARD WHERE BOARDNO=8);



INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, (SELECT GROUPNO FROM ANSWERBOARD 
 WHERE BOARDNO=2),
(SELECT GROUPSQ FROM ANSWERBOARD 
 WHERE BOARDNO=1)+1,
(SELECT TITLETAB FROM ANSWERBOARD 
 WHERE BOARDNO=2)+1,'RE:두번째 글', '2번글에 답글입니다(2) ', '유저2' , SYSDATE
);

--ROW 삭제
DELETE FROM ANSWERBOARD WHERE BOARDNO = 7;

--2번째 글에 대한 답글
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSQ.NEXTVAL, (SELECT GROUPNO FROM ANSWERBOARD 
 WHERE BOARDNO=8),
(SELECT GROUPSQ FROM ANSWERBOARD 
 WHERE BOARDNO=8)+1,
(SELECT TITLETAB FROM ANSWERBOARD 
 WHERE BOARDNO=8)+1,'RE:RE:두번째 글', '2번글에 답글입니다(1) ', '유저1' , SYSDATE
);

